#!/bin/bash
set -e
export GIT_VER_APP_VERSION="0.0.3-beta"
export GIT_VER_APP_DIR=$(dirname $(readlink -f $0))
main () {
    source "$GIT_VER_APP_DIR/git-ver.bashlib" #include the common library so everything in here can execute.
    if [[ $1 == version || $1 == help ]]; then
        bash "$GIT_VER_APP_DIR/git-ver-$1" ${*:2} 
    elif [ "$(is_in_git_repo)" == true ]; then
        command="$GIT_VER_APP_DIR/git-ver-$1"

        if [[ -f $command ]]; then
            export GIT_VER_REPO_ROOT="$(get_repo_root)"
            export GIT_VER_REPO_VERSION="$(get_version)"
            export GIT_VER_REPO_LATEST_TAG="$(get_tag)"
            export GIT_VER_REPO_BRANCH_NAME="$(get_branch_name)"
            bash $command ${*:2}
        else 
            echo >&2 "Unknown command: $1."
            bash "$GIT_VER_APP_DIR/git-ver-help"
            exit 1
        fi;
    else
        echo "The current directory isn't a git working tree. You must be in a git working tree to run this command"
        exit 2
    fi;
}
main $*