#!/bin/bash
set -e
get_script_dir () {
     SOURCE="${BASH_SOURCE[0]}"
     # While $SOURCE is a symlink, resolve it
     while [ -h "$SOURCE" ]; do
          DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
          SOURCE="$( readlink "$SOURCE" )"
          # If $SOURCE was a relative symlink (so no "/" as prefix, need to resolve it relative to the symlink base directory
          [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
     done
     DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
     echo "$DIR"
}
GIT_VER_DIR=$(get_script_dir)
pushd "$GIT_VER_DIR"
echo "
usage: git-ver get-version
get-version : Gets the version number in Major.Minor.Patch format. If none can be established, it uses 0.0.1.

To establish a version number the following steps take place:
    1. First git is interrogated for tags. 
    2. The tags are stripped of any non [0-9.] characters.
    3. The list is sorted highest to lowest and the highest value is chosen. Tag wisely so as not to break this feature.

If a suitable version is extracted from a tag it becomes the candidate version number. A candidate can be overridden when any of the following occur:
    1. An APP_VEYOR_VERSION environment variable is set. 
    2. OR A VersionPrefix environment variable is set. 
    3. OR A Version environment variable is set.
    4. OR The current branch name starts with release

The contents of the environment variable are assumed to match the MAJOR.MINOR.PATCH format. Ensure that they do.

"