#!/bin/bash
GIT_VER_VERSION="0.0.1-alpha"
set +ex
get_script_dir () {
     SOURCE="${BASH_SOURCE[0]}"
     # While $SOURCE is a symlink, resolve it
     while [ -h "$SOURCE" ]; do
          DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
          SOURCE="$( readlink "$SOURCE" )"
          # If $SOURCE was a relative symlink (so no "/" as prefix, need to resolve it relative to the symlink base directory
          [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
     done
     DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
     echo "$DIR"
}
GIT_VER_DIR=$(get_script_dir)
command="bash $(get_script_dir)/git-ver-$1"

if [[ -f "$GIT_VER_DIR/git-ver-$1" ]]; then
    ( export GIT_VER_VERSION; $command ${*:2} )
else 
    echo >&2 "Unknown command: $1."; 
    exit 1; 
fi;