#!/bin/bash
set -e
get_script_dir () {
     SOURCE="${BASH_SOURCE[0]}"
     # While $SOURCE is a symlink, resolve it
     while [ -h "$SOURCE" ]; do
          DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
          SOURCE="$( readlink "$SOURCE" )"
          # If $SOURCE was a relative symlink (so no "/" as prefix, need to resolve it relative to the symlink base directory
          [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
     done
     DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
     echo "$DIR"
}
get_suffix() {
    GIT_VER_DIR=$(get_script_dir)
    # local system defaults. These are overridden by appveyor
    local rev="$($GIT_VER_DIR/git-ver get-rev -a)"
    local suffix="$(git rev-parse --symbolic --tags | sort -i | tail -1 | sed -e 's/\(.*\)\([-]\)\(.*\)/\3/').$rev"
    local branch_name=$(git rev-parse --abbrev-ref HEAD)
    if [[ "$APPVEYOR" == true ]]; then
        rev=$APPVEYOR_PULL_REQUEST_NUMBER
    fi

    if [[ "$branch_name" == master ]]; then 
        suffix=""
    elif [[ "$branch_name" == "release/"* ]]; then 
        suffix="rc"
    elif [[ "$branch_name" == develop ]]; then 
        suffix="pre"
    elif [[ "$branch_name" == "feature/"* ]]; then 
        suffix="beta"; 
    else
        suffix="alpha"; 
    fi

    if [[ ( "$1" == "--rev" || "$1" == "-r" ) && "$rev" -gt 0 && "$suffix" != "" ]]; then suffix="$suffix+r$rev"; fi
    if [[ ( "$1" == "--date" || "$1" == "-d" ) && "$rev" -gt 0 && "$suffix" != "" ]]; then suffix="$suffix+d$(date -u '+%Y%m%d.%H%M%S.00')"; fi

    echo $suffix
}
get_suffix $1