#!/bin/bash
set -e
get_rev() {
    local rev=0
    # count commits since last tag in this branch
    local last_tag=$(git rev-list --tags --no-walk --max-count=1)

    if [[ "$last_tag" == "" || $1 == "--all-commits" || $1 == "-a" ]]; then
        # There is no tag yet, so we have no "baseline" or inferrable version number
        # count all commits in this branch. .
        foo=$(git rev-parse --abbrev-ref HEAD)
        rev=$(git rev-list --no-merges --count $foo)
    elif [[ "$last_tag" == "" || $1 == "--repo" || $1 == "-r" ]]; then
        rev=$(git rev-list --no-merges --count --all)
    else
        # count commits since last tag
        rev=$(git rev-list $last_tag..HEAD --count)
    fi
    
    echo "$rev"
}
get_rev $1