#!/bin/bash
set -e
if [[ "$1" == "" ]]; then
echo "
usage: git-ver [command] [command arguments]
       git ver [command] [command arguments]
       
For more details on the individual commands type git-ver help [command]

List of known commands:
get-major   : Returns the major number from the current semantic version number. (Maj.Min.Patch[-info+metadata])

get-minor   : Returns the minor number from the current semantic version number.

get-patch   : Returns the patch number from the current semantic version number

get-prefix  : Returns the version with a prefix, prefix defaults to 'v'

get-repo-root : Gets the full path to the root of the current repository

get-rev     : Counts the number of commits from the last tag and returns that as a revision number. (placed in info as .rev#)

get-semver  : Retrieves a full semantic version, optionally with metadata (+r1; +dYYYYMMDD-hhmmss)

get-suffix  : gets the suffix for a pre-release semantic version. (e.g. -alpha.1)

get-version : Gets the version number in Major.Minor.Patch format

help        : Displays this help information.

"
else
    if [[ -f "$GIT_VER_APP_DIR/git-ver-help-$1" ]]; then
        ( export GIT_VER_APP_VERSION; "$GIT_VER_APP_DIR/git-ver-help-$1" )
    else 
        echo >&2 "Couldn't find help for: $1."; 
        exit 1; 
    fi;
fi;